# Obter usuários
GET http://localhost:3000/api/clients
Content-Type: application/json
###

# Inserir usuário
POST http://localhost:3000/api/clients
Content-Type: application/json

{
    "name": "João Silveira",
    "email": "joao@email.com"
}
###